### ISSUE TITLE
RPC not found

### ISSUE THREAD

**Issue by iv7dev** [aws-samples/aws-besu-realdigital#3]
Hi! please, help me with this.
Everything was deployed perfectly, but I can't access the rpc to configure the wallet.
cmd: `curl -v -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' "http://${ELB}/rpc"`
```
Note: Unnecessary use of -X or --request, POST is already inferred.
* Could not resolve host: rpc
* Closing connection
curl: (6) Could not resolve host: rpc
```
and is there any initial token minting? where?
Thanks and apologies.

**Comment by gucarreira** [comment]
Hello @iv7dev 

I don't if you fix the ingress annotations using the helm chart version = "4.7.1", please do, I answer the other issue with the path.

Please check if Load Balancer is active `kubectl get ingress -n besu` or if terraform resource is applied `tf state list | grep ingress-rules-besu` or the second ingressclass `network-nginx` was deployed.

For reason that I don't know the second ingress `besu-ingress-routes` isn't using the same LB to deploy the paths like `/rpc` or `/member-1` 

I will investigate.

And the second questions is YES, I will add some examples the get the address and accounts that is deployed in genesis file.

Thank you
