### ISSUE TITLE
Error Ingress Monitoring

### ISSUE THREAD

**Issue by iv7dev** [aws-samples/aws-besu-realdigital#5]
when deploy this:
```
#Deploy Besu
terraform apply -target helm_release.bootnode-2 -auto-approve && \
terraform apply -target helm_release.validator-4 -auto-approve && \
terraform apply -target helm_release.member-2 -auto-approve && \
terraform apply -auto-approve
```
![Screenshot_2023-09-25-10-30-57_1920x1080](https://github.com/aws-samples/aws-besu-realdigital/assets/90148722/c84fe595-392a-4f21-97dc-d565f72b4477)

**Comment by gucarreira** [comment]
Hello @iv7dev,

We identified a recently new version deployed by kubernetes/ingress-nginx. The latest version is [helm-chart-4.8.0](https://github.com/kubernetes/ingress-nginx/releases/tag/helm-chart-4.8.0).

If you fix the version to [helm-chart-4.7.1](https://github.com/kubernetes/ingress-nginx/releases/tag/helm-chart-4.7.1) will work.

on file besu.tf add line on `version    = "4.7.1"` on line 119, the code will looks like below

```
  resource "helm_release" "ingress-nginx" {
  depends_on = [helm_release.monitoring]
  name       = "quorum-monitoring-ingress"
  repository = "https://kubernetes.github.io/ingress-nginx"
  chart      = "ingress-nginx"
  version    = "4.7.1"
  namespace  = kubernetes_namespace.k8s-besu-namespace.metadata.0.name
  wait       = "true"
```

We will fix that soon

thank you
